site_name: ABAP RESTful Application Programming Model
site_description: 'Learning Content for ABAP RESTful Application Programming Model (RAP)'
site_author: 'SAP Development Learning'
site_url: 'https://github.wdf.sap.corp/DevelopmentLearning/restful-abap'
repo_url: 'https://github.wdf.sap.corp/DevelopmentLearning/restful-abap/'
edit_uri: 'edit/master/docs'

theme:
    name: 'material'
    palette: ## Add this sub-section if you want to change the theme color
      - scheme: default
        primary: indigo
        accent: indigo
      - scheme: slate
        primary: red
        accent: red
    font:
      text: Roboto
      code: Roboto Mono

markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
  - search

extra_css:
    - css/extra.css

nav:
    - Course Overview: index.md
    - Table of Contents: toc.md
    - Module 1 - Unmanaged:
        - 1.1 Defining Data model: 'Unmanaged Implementation/DefiningDataModel/README.md'
        - 1.2 Creating an OData Service: 'Unmanaged Implementation/CreatingODataService/README.md'
        - 1.3 Read-only List Reporting Apps: 'Unmanaged Implementation/DevelopingReadOnlyListReport/README.md'
        - 1.4 Transactional Apps: 'Unmanaged Implementation/DevelopingUnmanagedTransactionalApp/README.md'    
    - Module 2 - EML: 
        - 2.1 Consuming Business Object using EML: 'eml/consumptionofeml/readme.md'
    - Module 3 - Managed: 
        - 3.1 Defining the Data Model with CDS: 'Managed Implementation/DataModelManaged/readme.md'
        - 3.2 Transactional App: 'Managed Implementation/DevelopingTransactionalAppM/README.md'
        - 3.3 Projection Layer: 'Managed Implementation/DevelopingProjectionLayer/README.md'
        - 3.4 Defining Business Services: 'Managed Implementation/DefiningBusinessServicesM/README.md'
        - 3.5 Implementing Actions, Validations, Determinations: 'Managed Implementation/DevelopingValidationsM/README.md'
        - 3.6 Authorization Control: 'Managed Implementation/DevelopingAuthorizationControlM/README.md'
        - 3.7 Draft Handling: 'Managed Implementation/DraftSemanticKey/README.md'
        - 3.8 Integrating Augment: 'Managed Implementation/Augment and Precheck/README.md'
        - 3.9 Virtual Elements: 'Managed Implementation/VirtualElement/readme.md'
        - 3.10 Integrating Additional Save and UnManaged: 'Managed Implementation/AdditionalandUnManagedSave/readme.md'
        - 3.11 BDEF Projection: 'Managed Implementation/DefiningBehaviordefinitionAM/README.md'
        - 3.12 Approver Projections: 'Managed Implementation/DefiningBusinessServicesAM/README.md'     
        - 3.13 Custom CDS Entity: 'Managed Implementation/CustomCDSEntity/readme.md'  
    - Module 4 - Testability:
        - 4.1. CDS-SQL Test Double Framework: 'Testability/CDS-SQL Test Double Framework/readme.md'
        - 4.2. Behaviour Test Double Framework: 'Testability/Behavior Test Double Framework/readme.md'
    - FAQ: FAQ.md
